const BASE_MOVIES_URL = 'https://api.nomoreparties.co';
const BASE_MAIN_API_URL = 'https://api.shakarova.nomoredomains.icu';

const DESKTOP_SCREEN_SIZE = 1280;
const TABLET_SCREEN_SIZE = 768;
const MOBILE_SCREEN_SIZE_L = 480;
const MOBILE_SCREEN_SIZE_S = 320;

const DESCTOP_ITEMS_TO_SHOW = 12;
const TABLET_ITEMS_TO_SHOW = 8;
const MOBILE_ITEMS_TO_SHOW = 5;

const DESCTOP_ITEMS_TO_SHOW_INC = 3;
const TABLET_ITEMS_TO_SHOW_INC = 2;
const MOBILE_ITEMS_TO_SHOW_INC = 2;

const SHORT_FILM = 40;

export {
    BASE_MOVIES_URL,
    BASE_MAIN_API_URL,
    DESKTOP_SCREEN_SIZE,
    TABLET_SCREEN_SIZE,
    MOBILE_SCREEN_SIZE_L,
    MOBILE_SCREEN_SIZE_S,
    DESCTOP_ITEMS_TO_SHOW,
    TABLET_ITEMS_TO_SHOW,
    MOBILE_ITEMS_TO_SHOW,
    DESCTOP_ITEMS_TO_SHOW_INC,
    TABLET_ITEMS_TO_SHOW_INC,
    MOBILE_ITEMS_TO_SHOW_INC,
    SHORT_FILM
}